name: "Build configurations"

on:
  push:
  workflow_run:
    workflows: ["Update sources"]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Determinate Nix with lazy trees enabled
        uses: DeterminateSystems/determinate-nix-action@main
        with:
          extra-conf: lazy-trees = true

      # - uses: cachix/install-nix-action@v27
      #   with:
      #     nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v15
        with:
          name: nightly-tools
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: "nix-community, niri, devenv, anyrun"

      - run: nix build .#all
