name: "Build configurations"

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: nightly-tools
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix build .#all

  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          name: nightly-tools
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix build .#all
